import { useState } from 'react';
import { socket } from '../socket';

export default function TeacherView() {
    // In a real app, this code would be generated by the server
    const [joinCode] = useState('123456');
    const [promptInput, setPromptInput] = useState('');
    const [sessionState, setSessionState] = useState<'IDLE' | 'ACTIVE'>('IDLE');

    const startSession = () => {
        // Join the socket room as a teacher
        socket.auth = { role: 'TEACHER' };
        socket.connect();
        socket.emit('JOIN_ROOM', { joinCode });
        setSessionState('ACTIVE');
    };

    const sendPrompt = () => {
        if (!promptInput.trim()) return;
        socket.emit('TEACHER_SEND_PROMPT', { joinCode, content: promptInput });
        alert(`Sent prompt: "${promptInput}"`);
        setPromptInput('');
    };

    const triggerSwap = () => {
        socket.emit('TRIGGER_SWAP', { joinCode });
        alert('Swapping responses...');
    };

    if (sessionState === 'IDLE') {
        return (
            <div style={{ textAlign: 'center', marginTop: '2rem' }}>
                <h1>Teacher Dashboard</h1>
                <button onClick={startSession}>Start New Session (Code: {joinCode})</button>
            </div>
        );
    }

    return (
        <div style={{ padding: '2rem', maxWidth: '800px', margin: '0 auto' }}>
            <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h1>Teacher Dashboard</h1>
                <div style={{ background: '#eee', padding: '0.5rem 1rem', borderRadius: '8px' }}>
                    <strong>Join Code: </strong>
                    <span style={{ fontSize: '1.5rem', color: '#646cff' }}>{joinCode}</span>
                </div>
            </header>

            <hr />

            <div style={{ display: 'grid', gap: '2rem', marginTop: '2rem' }}>
                <section className="card">
                    <h3>1. Send a Prompt</h3>
                    <div style={{ display: 'flex', gap: '1rem' }}>
                        <input
                            type="text"
                            value={promptInput}
                            onChange={(e) => setPromptInput(e.target.value)}
                            placeholder="e.g., What is the definition of..."
                            style={{ flex: 1, padding: '0.5rem' }}
                        />
                        <button onClick={sendPrompt}>Send</button>
                    </div>
                </section>

                <section className="card">
                    <h3>2. Manage Responses</h3>
                    <p>When students have submitted their thoughts, click below to shuffle.</p>
                    <button onClick={triggerSwap} style={{ backgroundColor: '#ff6b6b' }}>
                        🔀 Swap & Distribute Thoughts
                    </button>
                </section>
            </div>
        </div>
    );
}